name: Docker Image CI

on:
  push:
    branches: [ "" ]
  pull_request:
    branches: [ "main" ]

env:
  IMAGE: stable-studio

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Run install
      uses: borales/actions-yarn@v4
      with:
        cmd: install # will run `yarn install` command
    - name: Build production bundle
      uses: borales/actions-yarn@v4
      with:
        cmd: build # will run `yarn build:prod` command
    - name: Docker Login
      uses: docker/login-action@v2.2.0
      with:
        # Username used to log against the Docker registry
        username: ${{secrets.REGISTRY_USER}}
        # Password or personal access token used to log against the Docker registry
        password: ${{secrets.REGISTRY_TOKEN}}
    - name: Build and Push the Docker image
      uses: docker/build-push-action@v4.1.0
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{secrets.REGISTRY_USERNAME}}/${{env.IMAGE}}:latest
